image: docker:latest

# services:
#   - docker:dind

# variables:
#   # Set the Docker host for the Docker client to connect to the daemon
#   DOCKER_HOST: tcp://docker:2375/
#   # Disable TLS as it's not required for this setup
#   DOCKER_TLS_CERTDIR: ''

stages:
    - build-develop
    - deploy-develop

build-develop:
    stage: build-develop
    rules:
        - if: $CI_COMMIT_TAG =~ /^dev-\d+.\d+.\d+-?.*$/
          when: always
    tags:
        - ba-dedicate-task
    script:
        - echo "Building to Develop..."
        - docker build -t ba-application-ui-dev -f Dockerfile.dev .

deploy-develop:
    stage: deploy-develop
    rules:
        - if: $CI_COMMIT_TAG =~ /^dev-\d+.\d+.\d+-?.*$/
          when: always
    tags:
        - ba-dedicate-task

    script:
        - echo "Deploy to Docker..."
        - docker rm -f ba-application-ui-dev
        - docker run -d -p 3000:3000 --restart always --name ba-application-ui-dev --net nginx-proxy-manager-installation-docker_default --ip 172.18.0.4 -e ENV_APP=dev ba-application-ui-dev:latest
